[package]
name = "docker-rust"
version = "0.0.1"
authors = ["yusuke <yusuke@newsdict.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
