version: "3"
networks:
  app-tier:
    driver: bridge
services:
  node:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/rust
    working_dir: /rust
    command: "/root/.cargo/bin/cargo run"
    ports:
      - 3000:3000
    networks:
      - app-tier