version: "3"
networks:
  app-tier:
    driver: bridge
services:
  node:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - 3000:3000
    networks:
      - app-tier