[development]
address = "0.0.0.0"
port = 3000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
secret_key = "5OSdteNAbJT+JrMXQJ0yVd8pXEit1c/ibBuHqKmqeUs="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 3000
workers = 2
keep_alive = 5
log = "critical"
secret_key = "vK303vl1yBH/ixpniQepkab4asPj7bQ6hI+CTVG0unQ="
limits = { forms = 32768 }